### ISSUE TITLE
Resolve IPs to local host names

### ISSUE THREAD

**Issue by jtenniswood** [MrKsey/AdGuardHome#1]
Is it possible to give clients a name rather than just the IP address?
I had previously used the --add-host="client:192.168.x.x" command but that doesn't seem to work in this container. Any suggestions?
Thanks, loving the work!

**Comment by MrKsey** [comment]
Ok i'll check

**Comment by MrKsey** [comment]
> I had previously used the --add-host="client:192.168.x.x" command but that doesn't seem to work in this container. Any suggestions?

Just checked:
`docker run --add-host=desktop-one:192.168.1.123 --name AdGuardHome -d -p 192.168.1.252:53:53/udp -p 3000:3000 -v/AdGuardHome:/opt/AdGuardHome/config ksey/adguardhome`

`docker exec -i -t AdGuardHome /bin/bash`

```
cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.1.123   desktop-one
```
But it seems that AdGuardHome does not use the file `/etc/hosts`. This is not a container problem.
Please contact the AdGuardHome developers - [AdguardTeam/AdGuardHome](https://github.com/AdguardTeam/AdGuardHome)
