### ISSUE TITLE
docker pulls Version:  0.103.3

### ISSUE THREAD

**Issue by bcookatpcsd** [MrKsey/AdGuardHome#3]
Hey there, 

I am *brand* new to docker.. I might be doing something wrong.. but 

docker pull ksey/adguardhome:latest
latest: Pulling from ksey/adguardhome
Digest: sha256:d7490ecbd813106d39e8ce302ede70b79a65d30c8cade5cc8f6a4b11353b1f3b
Status: Image is up to date for ksey/adguardhome:latest
docker.io/ksey/adguardhome:latest

and the gui shows 0.103.3 in the bottom.. Did I do something wrong?

**Comment by MrKsey** [comment]
> Hey there, 
> 
> I am *brand* new to docker.. I might be doing something wrong.. but 
> 
> docker pull ksey/adguardhome:latest
> latest: Pulling from ksey/adguardhome
> Digest: sha256:d7490ecbd813106d39e8ce302ede70b79a65d30c8cade5cc8f6a4b11353b1f3b
> Status: Image is up to date for ksey/adguardhome:latest
> docker.io/ksey/adguardhome:latest
> 
> and the gui shows 0.103.3 in the bottom.. Did I do something wrong?
> 
> 

Please use the official docker image: https://hub.docker.com/r/adguard/adguardhome
